### ISSUE TITLE
Preference setting - unclear meaning

### ISSUE THREAD

**Issue by shinkolobwe** [GIScience/ors-map-client#101]
Hello

The meaning of the preference setting “Convert stop after route ending to destination” is quite unclear to me. I do not understand what is meant here. I would suggest that another title is used for this setting.

Best wishes
Christian

**Comment by amoncaldas** [comment]
Hey.
Consider the following case: you have a route with points A, B and C. Then you right click on a place that is visually after the point C. There are two way to deal with it: append a point P and convert it to the route ending, or keep the original route ending and make the route go A, B, then P and then return to C (the original route endpoint). this options controls it.

**Comment by shinkolobwe** [comment]
ok thanks for the explanation. I think this is a useful setting. However, the designation is nevertheless confusing. The distinction between the terms "route ending" vs. "destination" remain unclear. "destination" would be considered by most users as the "final destination". The term "route ending" is not well chosen. It is a mix of noun and verb. Maybe some other users can come up with a better designation for the setting.

**Comment by amoncaldas** [comment]
Hey
Yes, the distinction between the terms "route ending" vs. "destination" is unclear and that is why it was chosen, as a synonym, so we avoid repeating the same word. Otherwise the sentence would be "Convert stop after destination to destination".

**Comment by amoncaldas** [comment]
If you have a suggestion that could replace the phrase, then this issue can be reopen and we (re)evaluate it. Thanks for the insights.

**Comment by koebi** [comment]
If I understand this correctly, this option is used to change the behaviour of the `Add stop here`-option in the right-click menu.
The default behaviour with this option turned off is to add a new stop before the current destination, as a second-to-last waypoint.
The behaviour with this option turned on is to add new stops "intelligently", using some kind of heuristic or optimization approach

I think the name of this option should reflect what it does, which is changing the behaviour of the `Add stop here`-option.
As such, I would suggest to rename to "Make `Add stop here` intelligent" or something that reflects the algorithm used to add points to the route, e.g. "`Add stop here` optimizes route".

**Comment by shinkolobwe** [comment]
"Allow re-ordering of waypoints to optimize route"

**Comment by amoncaldas** [comment]
The option was rephrased to "Convert stop added at the end of the route to final destination"
closed via https://github.com/GIScience/ors-map-client/commit/1d562c6f294c1995cb93ec3f576fea5d4f1b660a
