### ISSUE TITLE
More place inputs and/or multiple routes support

### ISSUE THREAD

**Issue by dcbr** [GIScience/ors-map-client#104]
Hi there,

First of all thank you for this great web app! I would like to use this to plan and store (locally in geoJSON format) hiking trails, as it seems to be the most flexible and detailed compared to all other online services I tried so far.
There are however 2 restrictions in place right now, that limit the creation of longer trails (e.g. for multi day trips) or the addition of manually defined 'alternative paths':

1. The active route can only have 15 waypoints, afterwards the 'add place input' button is removed.
2. There's no possibility (as far as I know) to add a second (alternative) route. However, when I manually change the geoJSON (by merging 2 downloaded routes) and reupload it, the app seems to correctly recognize these 2 (or more) routes, which is really great already. As soon as you start changing any of the points, the routes collapse to a single route instance again though.

Maybe supporting multiple routes is too much 'out of scope' for this project, but lifting the first restriction would definitely be helpful to (re)create longer trails. Especially when planning routes in 'shortest distance' mode, you need quite a lot of waypoints to exactly match your desired route.
I can try to work on this in my free time, but I first wanted to hear your opinion about this (general usefulness, possible pitfalls).

**Comment by amoncaldas** [comment]
Hey @dcbr 
It is good to know that you like the app. Thanks!

I just changed the maximum allowed place inputs to 50, which is the maximum points supported by the API.
Enjoy!
