### ISSUE TITLE
[Object Object] showing up in "Avoid features" menu

### ISSUE THREAD

**Issue by koebi** [GIScience/ors-map-client#107]
Here's a screenshot showing the option :)
![Screenshot_2021-03-16 Ors Maps](https://user-images.githubusercontent.com/4692974/111296744-1e118300-864d-11eb-90de-c69b5a005975.png)

**Comment by amoncaldas** [comment]
Thanks for reporting @koebi.
I could reproduce it and identify the buggy code.

**Comment by amoncaldas** [comment]
Fixed
