### ISSUE TITLE
map shows wrong points on place selection

### ISSUE THREAD

**Issue by koebi** [GIScience/ors-map-client#120]
Here's what I did:

1. Goto client, type some address in search, click `Directions`
2. End up with this:
![Screenshot_2021-04-13 ORS Maps(3)](https://user-images.githubusercontent.com/4692974/114547439-be63c300-9c5e-11eb-87e3-b591a972df00.png)

The place I searched for is put into the `Destination` Field, but is green and has a `1` on the map.

**Comment by amoncaldas** [comment]
Closed via https://github.com/GIScience/ors-map-client/commit/1d562c6f294c1995cb93ec3f576fea5d4f1b660a
