### ISSUE TITLE
Changing starting place doesn't update map

### ISSUE THREAD

**Issue by koebi** [GIScience/ors-map-client#121]
Here's what I did:
1. Goto client, type some address in search, click Directions
2. Get this:
![Screenshot_2021-04-13 ORS Maps(3)](https://user-images.githubusercontent.com/4692974/114547637-f79c3300-9c5e-11eb-8d4d-0b4819cf7d8e.png)
3. Drag `(2) Destination` to `(1) Starting Place`
4. Change `(1) Starting Place` to some other address
5. end up with this:
![Screenshot_2021-04-13 ORS Maps(2)](https://user-images.githubusercontent.com/4692974/114547801-2fa37600-9c5f-11eb-9781-35104b6ede50.png)

**Comment by amoncaldas** [comment]
Hey. It seems that you have two place input fields and only one is filled.
The app was designed in a way that if you want to focus in one place (go to place mode, what changes the URL to /place/...) you have to remove the empty place input. But, if you want to calculate a route (when you have at least two inputs) you have to type/select a place for the input that is empty. 

But I agree that if you changed the address, it should reflect in the map view. I will check this soon.

**Comment by amoncaldas** [comment]
Closed via https://github.com/GIScience/ors-map-client/commit/1d562c6f294c1995cb93ec3f576fea5d4f1b660a
