### ISSUE TITLE
Avoidables carried over to profiles where they are invalid

### ISSUE THREAD

**Issue by rabidllama** [GIScience/ors-map-client#122]
When you select an avoid features option in one profile and then switch to another where this avoidable is not available, the system shows an "Invalid parameter" message, but the avoidable doesn't show in the list so I have to go back to the original profile and deselect it before switching profiles. Ideally the system should strip out the avoidable that isn't valid when the profile is changed.

Here's what I did:
1. Generate a car route with tollways set as avoid features:
![image](https://user-images.githubusercontent.com/7126643/114577534-5fad4200-9c7c-11eb-8fd9-4d35aed4c034.png)

2. Switch to a non-driving profile
![image](https://user-images.githubusercontent.com/7126643/114577629-7358a880-9c7c-11eb-8b03-4c8434944301.png)

**Comment by amoncaldas** [comment]
Closed via https://github.com/GIScience/ors-map-client/commit/1d562c6f294c1995cb93ec3f576fea5d4f1b660a
