### ISSUE TITLE
drawbacks of componentwise translation 

### ISSUE THREAD

**Issue by koebi** [GIScience/ors-map-client#124]
As I understand it, there exists one global translation file for global settings and common words like month names, units and stuff.
Then, each component has its own translation file for each language.

In my eyes, this comes with two drawbacks:
* Currently, there are a 36 translation files (compare #123). As more components get developed, this number will probably rise.
For anybody willing to contribute a translation, this leads to a non-negligible overhead in copying and translating files.
* The translation files inevitably contain duplication.

I think there are a few different ways we could implement to make this system easier:
* merge all translations into one big file, as with the old client
* automatic merging and unmerging to be able to provide translators with one big file
* use an external platform such as [weblate](https://weblate.org/en/) for translation

I don't think this is too urgent or something that needs a fix right now, but I'd like to get your opinion on this matter :)

**Comment by amoncaldas** [comment]
Hi @koebi 

The thing is that, as explained in the readme, the app was designed to use the feature-by-folder design, so each component is intended to be, at some level, an isolated unit, that communicates with other components via parameters and events. the idea is that by adding or modifying a component, you won't mix up other logic units (components). For example, if there is only a global list of translation key/strings someone could change the string of a translation key with the intention of adapting it for a component, but it could affect other components using the same translation key/string for a different case. Said that, I agree that it brings some considerable extra work for people willing to contribute with a translation. Maybe this is too purist? So far I think it's worth it, but we can certainly discuss this.

But in fact, the possibility of "automatic" merge translation into one big file already existed. I used it  locally when I had to send it to a fellow who created the Italian translation. It was just not documented. Now I documented it. You can check the instructions here: [https://github.com/GIScience/ors-map-client#--generate-a-translation-file](https://github.com/GIScience/ors-map-client#--generate-a-translation-file).

**Comment by amoncaldas** [comment]
As the automatic merging in one big file is already in place, I will consider it as done for now.
