### ISSUE TITLE
orsteingabe openrouteservice

### ISSUE THREAD

**Issue by ThomasMueller98** [GIScience/ors-map-client#127]
Bei der Eingabe ( Android) sind die Ortsnamen schlecht lesbar und Ziel kommt anscheinend zuerst.
Erstes verwirrend.
Gruß
Thomas

**Comment by amoncaldas** [comment]
Hallo @ThomasMueller98 

Könnten Sie bitte ein konkreteres Beispiel geben? Vielleicht würde ein Screenshot helfen.

**Comment by ThomasMueller98** [comment]
Ja klar. Ist per Mail gerade unterwegs
Danke für die schnelle Antwort
Guten Tag
Ihr habe mir ein Routing gemacht von Pforzheim nach München. Trekking.
Um Augsburg herum gab
es plötzlich viele Radwege zu gehen. Teer belag.

Wohin kann ich meine Erfahrungen zu OSM senden?

Super Arbeit. Vielen Dank.

Gruß



Amon Caldas ***@***.***> schrieb am Di., 20. Apr. 2021, 10:19:

**Comment by amoncaldas** [comment]
@ThomasMueller98 
Bitte hängen Sie das Foto hier im GitHub-Thread an, damit wir den Verlauf behalten und andere Personen sehen können.

**Comment by amoncaldas** [comment]
As no further information was provided, this issue is being closed. It can be reopened again if needed.

**Comment by Jelizog** [comment]
Hello there,
We building a java app from the android studio and we need help to connect our app with the openrouteservice so our users (only with wheelchairs) can get directions from their location to the pin they need. Something to suggest? 
Thank you
Jordan

**Comment by koebi** [comment]
Hey,
comments on closed github issues are not the best way to ask for help ;)
Head over to our [community forum](ask.openrouteservice.org) and *search the issues there*! Maybe there is already someone with a similar problem and a solution. If not, feel free asking over there.

Best regards
