### ISSUE TITLE
Isochrone method `time` not working

### ISSUE THREAD

**Issue by sfendrich** [GIScience/ors-map-client#128]
**What I did:**

1. Enter "maps.openrouteservice.org" in Firefox
2. Click on "Directions"
3. Click on "Reach"
4. In options "isochrone method", select "Time"
5. Rightclick on map and select "Add as reach center"

**What I got:**
Error message "One or more parameters have an incorrect value or format."

**What I expected:**
Display of isochrones around the reach center.

**Comment by koebi** [comment]
There is a related [comment in the ask-forum](https://ask.openrouteservice.org/t/isochronen-typ-zeit-fehlermeldung-wert-format/2709).

When looking at the issued `POST`-request, it doesn't set the range correctly, which the isochrones-endpoint requires.
In fact, changing either of the two controls (range and interval) doesn't do anything.

**Comment by TheGreatRefrigerator** [comment]
Seems to be an issue with the remove invalid filter and range listing in the config file
https://github.com/GIScience/ors-map-client/commit/1d562c6f294c1995cb93ec3f576fea5d4f1b660a#diff-4f36ad49d7f622d8a085ab75ee40e24bd3d17635646e97105dad4d8ee9c5cab0R160-R183

**Comment by amoncaldas** [comment]
Thank you guys.  I think it was introduced accidentally when I fixed another bug. My bad. I will check it very soon.

**Comment by amoncaldas** [comment]
Fixed via https://github.com/GIScience/ors-map-client/issues/128
