### ISSUE TITLE
Hungarian translation ready

### ISSUE THREAD

**Issue by debyos** [GIScience/ors-map-client#129]
Dear @amoncaldas & everyone who may be concerned,

I have completed the [Hungarian translation of ORS](https://github.com/GIScience/ors-map-client/files/6372844/hu-translation-source-merged.zip). Thus, please, deploy it and then I try to verify if everything was made fine.
Thanks for all of your help

Gábor

**Comment by amoncaldas** [comment]
Hey @debyos 
Could you please test the Hungarian translation here https://vue.openrouteservice.org and provide a feedback? If it is ok, I will then deploy to the production environment.

**Comment by debyos** [comment]
Hi @amoncaldas,

I have tested the Hungarian translation and made a number of changes [you can find here](https://github.com/GIScience/ors-map-client/files/6387642/hu-translation-source-merged.zip). You can now deploy it.

The Leaflet.draw.locales apparently [does include a HU version](https://github.com/DenisCarriere/Leaflet.draw.locales/blob/master/src/locales/hu.ts) so you might consider to use that. (Or I can provide you a translation promptly.)

Also, I am keen to translate the routing instructions which may be somewhere else.

Best wishes

_Gábor_

**Comment by amoncaldas** [comment]
Hi @debyos 
The Hungarian locale was added and deployed with the updated you sent.
Although apparently the Hungarian locale is listed as supported in the Leaflet.draw.locales, it just throws an error when it is called passing the 'hu', like the example they provide:

```js
import drawLocales from 'leaflet-draw-locales'

// Automatically defines Leaflet.draw to the specified language
drawLocales('hr')
```

Our code that runs it can be found here https://github.com/GIScience/ors-map-client/blob/84af48bbad1a65adaa39d48fa3b6af5e3589a631/src/fragments/map-view/map-view.js#L1634

**Comment by debyos** [comment]
Dear @amoncaldas,

thanks for the explanations. As far as the drawing tool is concerned, it is too technical for me, so I can't help or do anything.

However, I have found the [routing instructions in Hungarian](https://github.com/GIScience/openrouteservice/blob/104371bb60298f90641908a1d11e3e6a6325eace/openrouteservice/src/main/resources/resources/locales/ors_hu-HU.resources), and I have instantly updated them. They were pretty much in need of it… You can find [the results attached here](https://github.com/GIScience/ors-map-client/files/6399800/ors_hu-HU.resources.zip).

Thus, please deploy them as well, perhaps first on [vue.openrouteservice.org](http://vue.openrouteservice.org).

Thanks

_Gábor_

**Comment by amoncaldas** [comment]
Hey @debyos 

Would you be available to translate/update new strings if we do some update/change in the webapp? This is usually an issue, since we need to maintain/evolve the app along the time.

Regarding the instructions translations I would kindly ask you to follow this https://github.com/GIScience/openrouteservice/wiki/Contributing-Translations instructions to submit it. There is a separated project and team working on the API.

**Comment by debyos** [comment]
Dear @amoncaldas,

I have spotted a minor mistake in the [right click label file](https://github.com/GIScience/ors-map-client/blob/f2879ccddf747555dd06735337332ad36c227651/src/fragments/map-view/components/map-right-click/i18n/map-right-click.i18n.hu-hu.js).

[A correction can be found here.](https://github.com/GIScience/ors-map-client/files/6407944/map-right-click.i18n.hu-hu.zip)

If you happen to have some time, you might update it.
Thanks

_Gábor_
