### ISSUE TITLE
Clicking `Directions` drops input

### ISSUE THREAD

**Issue by koebi** [GIScience/ors-map-client#132]
Here's what I did:
1. goto maps.openrouteservice.org
2. Enter some search (e.g. "Katzenbuckel") in `Find a place`
3. get no instant results, so click on `Directions`-Button
4. get empty sidebar

Here's what I'd have expected
4. get sidebar with "Katzenbuckel" (i.e., my input) in `Destination`-Field.

**Comment by amoncaldas** [comment]
Hey @koebi 
Considering that a place input is only considered filled when the user selects a suggestion on the list, wouldn't what you're suggesting lead to confusion, once the user would see the input apparently "filled" and go to the next step (fill the origin)?

**Comment by koebi** [comment]
I think the fact that the input is only considered filled once a suggestion is selected is already confusing in the first place.
Given that, if the suggestion-list is opened in the sidebar, this should make it clear that the destination is not filled correctly.

**Comment by amoncaldas** [comment]
Hey @koebi 
Thank you for your thoughts.

I'm not sure if I got your point right about "the fact that the input is only considered filled once a suggestion is selected is already confusing in the first place". I will provide my comments based on what I understood (you can correct me if I got if wrong):
The thing is that the place selection is done by converting a text into coordinates and the client consumes the geocoder service that returns a collection of places based on the text inputted by the user. So, this process of determining a location based on a text needs the user action of selecting one of the suggestions. Although the geocoder returns the suggestions ordered by what could it considers the best match, this is very far from being something we could rely on to automatically pick the first item and not give the user the option to choose by him/her self the item that matches his/her expectation. A similar approach of type is used by other maps client.

Are you suggesting that if the user types a text, do not select a suggestion manually and then hit the directions button, the app should assume the first item of the suggestion list (if there are suggestions) as the selected one?

**Comment by amoncaldas** [comment]
Closed due to inactivity. Can be reopened at any time to continue the discussion and to define possible changes.
