### ISSUE TITLE
Adding a via by drag and drop should not zoom or pan the window

### ISSUE THREAD

**Issue by BobLemon23** [GIScience/ors-map-client#138]
In the current implementation, adding a via point by drag and dropping the route causes the view to zoom and pan to show the entire route.

This makes making minor changes to routes extremely annoying for no real benefit (zooming and panning to the entire track can easily be done manually, if the user chooses to).

**Comment by amoncaldas** [comment]
Hey @BobLemon23 
There is an option that controls this called **Always fit bounds when route changes** in app settings https://maps.openrouteservice.org/#/settings -> **Map view and extra information**
