### ISSUE TITLE
Feature request: cross-reference route position from elevation profile, and vice-versa

### ISSUE THREAD

**Issue by jayaddison** [GIScience/ors-map-client#140]
This issue report relates to the usability and functionality of the elevation profile / altitude profile feature in the responsive maps client (pictured below).

![image](https://user-images.githubusercontent.com/55152140/120121784-4cf3bb80-c19d-11eb-8e4b-416a14cdb381.png)

As reported at [`ask.openrouteservice.org` here](https://ask.openrouteservice.org/t/feature-request-side-by-side-rendering-of-route-progress-dot-and-elevation-profile-altitude-progress-dot/2849), it can be useful to have a way to cross-reference positions on the route and elevation profile during journey planning.

Although there is a workaround / solution available involving opening the `Leaflet.Heightgraph` popout by clicking the 'Expand chart' icon, it would be nice to incorporate this kind of altitude-to-route (and ideally route-to-altitude) display cross-referencing into the default elevation profile that is shown to users.

**Comment by jayaddison** [comment]
Please note: this may be related to #14.  At the time of writing this report, it doesn't appear possible to use mouseover to cross-reference altitudes and route positions using the default elevation profile (as shown in the description screenshot).

**Comment by amoncaldas** [comment]
Hey @jayaddison 
Thanks for opening the issue.
I have already tested it some time ago and the thing is that as the width of the altitude preview box is limited, the resolution of the chart is reduced and the usability is not good (it is difficult to put the mouse over an desired point). The sidebar chart must be seen as a preview and the full feature is available on the full chart (available with one click)

**Comment by jayaddison** [comment]
Thanks @amoncaldas; those limitations make sense, and the choice is a sensible trade-off.

I still believe it could be useful to provide this functionality to users without requiring previous knowledge of the icon and click action by them.

Although it might take me some non-trivial time to learn the codebase, I'll try to set up an instance of ORS and the client soon to learn a bit more about how it all fits together.  Any links to sections of the altitude map code in the client could be helpful, although I can probably narrow things down gradually given a bit of time to `grep` around.

**Comment by TheGreatRefrigerator** [comment]
@jayaddison not sure, how profound your `grep`ping skills are, but i highly suggest to use an IDE such as VSCode or WebStorm (free for students, or 30day trial) to easily cross-search the whole repo. But, if you are skilled with developing in console or normal text editors with plugins, feel free to do so :)

For the line chart in the sidebar see:
https://github.com/GIScience/ors-map-client/tree/c5193352baaa4ec43df1a9ceacb1d5d9f2c606de/src/fragments/charts
for most of the code.

The leaflet heightgraph overlay see:
https://github.com/GIScience/ors-map-client/blob/5398e04c07da1aa642e922cfeb198b35c03c96d4/src/fragments/map-view/map-view.js#L558-L602
and
https://github.com/GIScience/ors-map-client/blob/aec2442ba2004a185b9858172583a063942ef107/src/fragments/map-view/MapView.vue#L122

Best regards
