### ISSUE TITLE
isochrone calculation is broken

### ISSUE THREAD

**Issue by koebi** [GIScience/ors-map-client#142]
Sorry for the imprecise description, but it seems like isochrone calculation is broken in more than one way.

This was reported [in the ask-forum](https://ask.openrouteservice.org/t/isochronous-problem-map/2860/3).
I tried to reproduce it, and always came up with an isochrone view that was somehow broken in one of the following ways:

* changing range or interval didn't recalculate isochrones
* manually adapting the request in the url didn't do anything
* changing range re-issued a previous request (at least when looking at the url)

To reproduce, try the following:
* open sidebar -> reachability -> select `Gragnague` as place (calcs iso correctly)
* change type to `time`(same)
  this oddly seems to keep the range parameter value, which is sorta bad, since it'd convert e.g. 60km (60000m) to 60000s  (>16h).
* increase time (does nothing) 
From this point onwards, some actions seem to do something, some don't, but it's not clear to me why.

Also, the interval parameter doesn't seem to be respected - at least I wasn't able to calculate more than the one isochrone.
I also ran into a view where the map didn't zoom properly…

If I can provide more info to help debug this, let me know

**Comment by amoncaldas** [comment]
Fixed via https://github.com/GIScience/ors-map-client/commit/b2d0aac21701b4a8e35fd77b10bef804785d9c72 and https://github.com/GIScience/ors-map-client/commit/b2d0aac21701b4a8e35fd77b10bef804785d9c72
