### ISSUE TITLE
How to load default avoidance polygons ?

### ISSUE THREAD

**Issue by mastershaig** [GIScience/ors-map-client#146]
Hello,

What's the easiest way to load the default avoidance polygons before map loads ?

**Comment by amoncaldas** [comment]
Hi @mastershaig 
I will kindly ask you to post your question on our ask platform: https://ask.openrouteservice.org/c/maps/20, then it will answered there.
Thanks

**Comment by mastershaig** [comment]
Hi @amoncaldas,

Thanks for your response! Now I'm waiting for my account activation on [https://ask.openrouteservice.org](https://ask.openrouteservice.org).
