### ISSUE TITLE
Split screen different map types

### ISSUE THREAD

**Issue by BenasPaulikas** [GIScience/ors-map-client#149]
Is it possible to have split screen maps with 2 different map types(satellite + cycling map) and when i move one other would move too.

This really helps when planing offroad rides.

![image](https://user-images.githubusercontent.com/6473565/92757298-4797dc00-f396-11ea-83dc-bf7eb9b17db7.png)

**Comment by amoncaldas** [comment]
Hi @BenasPaulikas 
Technically it is possible, but it has to be implemented. Although it is an interesting feature, it is not our priority list at this moment. As the software is open source, you can potentially implement it and submit a push request with this feature.
