### ISSUE TITLE
Feature Request: Preview duration for each route setting

### ISSUE THREAD

**Issue by thibaultmol** [GIScience/ors-map-client#151]
Hi,

Something I’d like to see is on the ‘route preference’ slider to see the duration of each route above the dot on the slider.
That way I could easily see what the difference is in duration between the different routes

Cheers

**Comment by amoncaldas** [comment]
Hi @thibaultmol 
Could you please share a screenshot showing what exactly you would like as feature? I could not realize if by reading your text. Thanks

**Comment by amoncaldas** [comment]
Closed due to inactivity and lack of clarification. Can be reopened if a reply is provided.
