### ISSUE TITLE
Max. speed and corresponding filter widget not clearly communicated

### ISSUE THREAD

**Issue by bezin** [GIScience/ors-map-client#153]
Hello there, 

first of all thanks for this web service, as I use it regularly to plan my trips :-)

I noticed something strange concerning the max speed setting: For a fictionous trip from „Platz des Landtags, Düsseldorf“ to „Rathaus Essen“ I get the following results: 
 
– without any adjustment: 37:00 min.
– max. speed 120: 37:57 min.
– max. speed 100: 39:43 min.
– max. speed 80: 43:16 min.

First: What is the default value here? I guess, the client assumes, I will always go the max. allowed speed, if I do not set max speed manually?

Second: I think the UI is not very clear on this, as the max. speed widget does not communicate its „I don't do anything at the moment“ state very well.

What are other takes on this? Happy to hear your comments 👍

**Comment by amoncaldas** [comment]
Hi @bezin 
We are happy that you enjoy our services and client.

There is no default value. When no value is specified in the input, no maximum_speed parameter will be sent to the ORS API.

While checking the situation you  described, I noticed that it was not possible to reset the maximum speed input to its default state (no value). Once a maximum speed was defined, it was only possible to define a value between the max and minimum allowed. If was fixed via b40e279e69d6dae6d020e69edf197399460bedf6

Now with the possibility of removing any value (empty) state, I hope it will be clearer that this parameter is not being defined and therefore is in the "not used/defined" state. Adding some "disable" button would require additional space, which is not available when using it on mobile/low resolution devices.

But I still agree that it makes sense that `no maximum speed` parameter should produce the same result of setting the speed as the `maximum allowed`. But in this case, I believe we are talking about the ORS API backend. Maybe you want to create an issue in the [back-end repository](https://github.com/GIScience/openrouteservice) for this?

Cheers
