### ISSUE TITLE
hgv and wheelchair options (profile params) are visible in the other profile

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/ors-map-client#158]
e.g. `track_type` should only be visible for wheelchair
`width`, `height` etc. only for hgv

See also https://ask.openrouteservice.org/t/filtering-out-grade-of-tracks-for-bicycle-routing/2887/2

**Comment by amoncaldas** [comment]
Fixed via 97f1be1cee9365cb327aa3de4509ad0022b1712c
