### ISSUE TITLE
ask ors link should go to maps client category

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/ors-map-client#159]
The link from the info dropdown which goes to the ask forum should point to
https://ask.openrouteservice.org/c/maps/20

So people coming from the maps client will post in the maps client section

**Comment by amoncaldas** [comment]
Fixed via 97f1be1cee9365cb327aa3de4509ad0022b1712c

**Comment by TheGreatRefrigerator** [comment]
The link is now fixed on the about page.
The link in the info dropdown still goes to the main ask page 🔗 
![dropdown](https://user-images.githubusercontent.com/23240110/123825216-0362d180-d8ff-11eb-9f91-33d1b85d06a6.png)

**Comment by amoncaldas** [comment]
You are right, the drop-down had not been updated. It was fixed via e948e4a8fe421f58adc50667ec1935033ef6c914
