### ISSUE TITLE
(Long?) URLs don't load

### ISSUE THREAD

**Issue by wmuni** [GIScience/ors-map-client#163]
I have saved two different relatively long URLs that don't load the route they are supposed to represent:

```https://maps.openrouteservice.org/#/directions/R%C3%B6slau,BY,Deutschland/Philosophenweg,Zell%20im%20Fichtelgebirge,BY,Deutschland/Birkenb%C3%BChl,Schwarzenbach%20a.d.%20Saale,BY,Deutschland/Pavillon,Hof,BY,Deutschland/Vorstadt%202,Hof,BY,Deutschland/Dachser,Hof,BY,Deutschland/Saale,Berg,BY,Deutschland/Saaldorf%2095,Bad%20Lobenstein,TH,Deutschland/Wahretweg,Schleiz,TH,Deutschland/Hohenwarte-Blick,Hohenwarte,TH,Deutschland/Schillingstra%C3%9Fe,Rudolstadt,TH,Deutschland/Stadtmuseum%20Camburg,Camburg,TH,Deutschland/Amselweg,Reichardtswerben,ST,Deutschland/L%20180,Braunsbedra,ST,Deutschland/Vor%20dem%20Klausentor,Merseburg,ST,Deutschland/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,70,124,3,160,19,128,118,50,3,96,9,128,86,0,105,104,1,136,166,0,231,218,166,72,27,144,162,219,83,105,68,190,18,180,72,6,96,239,137,131,102,69,8,150,161,74,120,242,109,38,83,236,68,147,74,195,169,211,106,48,164,249,45,241,177,57,32,11,45,43,52,152,169,218,74,242,252,182,203,237,181,217,99,22,73,124,74,50,106,73,38,59,18,18,14,59,87,81,113,35,33,90,91,74,79,33,0,162,73,106,20,207,90,112,146,3,96,215,107,54,111,61,3,106,104,187,12,187,16,175,90,16,202,20,172,218,87,50,54,102,169,90,54,90,46,7,12,219,89,113,96,219,2,138,17,87,17,50,94,206,110,50,96,178,40,129,148,218,50,73,41,103,106,17,182,238,148,238,104,188,135,110,140,222,168,253,74,74,110,85,219,87,81,173,53,172,251,14,130,252,12,203,149,124,110,209,57,30,201,87,44,174,21,11,35,224,227,136,50,243,91,16,93,109,18,177,49,218,173,126,55,131,132,210,219,49,74,38,106,35,24,135,35,9,121,12,38,3,25,14,42,49,19,224,40,217,75,148,141,133,138,35,100,238,195,56,69,95,7,20,240,132,146,159,26,51,19,16,229,167,68,184,28,7,16,146,151,16,43,69,108,182,14,12,151,175,38,35,221,146,161,10,45,2,79,51,139,73,22,156,105,179,156,92,17,166,248,225,108,125,98,208,198,65,186,35,4,119,9,62,28,35,208,40,210,100,190,80,160,152,73,68,145,81,138,38,118,152,129,199,165,241,44,121,5,21,34,201,133,168,144,187,108,32,122,8,2,0,0,117,67,192,32,136,108,14,20,0,2,242,128,1,109,112,86,200,244,122,1,0,1,155,192,0,54,232,92,56,0,9,230,2,45,32,0,230,0,90,104,58,6,176,5,114,47,33,160,17,144,46,125,15,159,66,55,16,96,82,222,17,185,7,79,167,208,136,88,58,22,2,0,2,250,206,128,0```

and

```https://maps.openrouteservice.org/#/directions/Zinnleitenweg,R%C3%B6slau,Deutschland/Philosophenweg,Deutschland/Wasserwacht%20Schwarzenbach%20%2F%20Saale,Deutschland/Fische%20im%20Untreusee,Deutschland/Lamitz,Deutschland/J%C3%A4gerstra%C3%9Fe%2041,Hirschberg,Deutschland/Siedlungsweg,Blankenberg,Deutschland/Am%20Stausee,Deutschland/K%C3%BCnsdorfer%20Berg,Deutschland/L%202385,Deutschland/Advanced%20Compounding%20Rudolstadt%20GmbH,Rudolstadt,Deutschland/Schwarzburger%20Chaussee%2055,Rudolstadt,Deutschland/Bahnhofstra%C3%9Fe,Camburg,Deutschland/L%C3%B6wendenkmal,Deutschland/Merseburger%20Stra%C3%9Fe,Wei%C3%9Fenfels,Deutschland/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,70,124,3,160,19,128,14,1,216,40,25,128,6,50,3,101,162,253,111,192,22,6,1,160,21,150,163,152,247,103,196,173,6,0,153,198,213,174,192,55,33,34,101,197,151,111,142,173,18,13,219,81,235,183,191,66,36,40,206,19,33,174,134,243,136,151,197,40,201,58,162,150,209,239,168,190,27,46,216,151,16,212,95,171,82,49,70,73,30,50,27,66,29,55,113,10,38,6,115,120,250,22,10,57,5,103,106,74,21,90,24,141,77,55,12,141,6,42,15,6,124,30,82,192,178,90,106,63,106,98,154,241,58,110,62,34,118,13,67,70,206,45,124,64,138,113,124,112,150,113,30,113,118,85,118,55,54,138,35,23,41,78,102,75,5,6,50,124,45,97,234,78,198,40,150,237,29,6,12,141,169,154,30,94,246,114,42,31,77,74,62,113,73,178,21,216,138,30,26,200,146,64,158,14,1,229,158,27,58,70,124,55,19,26,141,66,184,101,166,93,64,176,35,232,193,33,133,168,182,114,25,16,25,160,249,73,188,84,51,164,55,194,80,240,213,97,204,55,11,20,170,82,123,24,182,189,49,52,195,74,54,98,72,138,188,98,23,143,163,227,81,157,168,236,88,175,76,164,103,97,84,168,32,223,3,61,198,162,48,72,250,52,85,34,218,196,82,146,216,54,158,50,146,35,228,66,144,37,4,26,29,24,80,43,9,248,240,82,182,22,17,153,68,44,106,176,158,163,37,59,39,77,169,147,101,200,156,15,7,30,130,107,228,107,84,84,241,27,205,46,71,137,9,148,171,85,163,68,212,111,99,245,129,49,33,182,181,85,81,34,198,158,97,102,177,17,198,83,100,115,240,41,84,181,137,167,81,210,105,29,161,161,83,92,31,64,117,145,217,218,135,45,159,173,35,44,214,77,20,50,57,93,62,20,246,132,78,182,1,57,95,108,181,97,208,98,53,96,249,156,138,195,142,61,42,13,182,131,145,179,219,42,221,149,207,81,178,152,25,166,24,164,165,68,26,0,211,70,209,144,125,226,115,226,17,74,163,154,132,200,50,189,21,45,155,66,144,200,162,133,43,115,63,84,215,172,144,244,210,247,77,26,166,167,80,161,11,63,106,100,157,209,161,196,64,130,64,228,106,6,204,39,184,138,9,132,103,113,225,66,5,133,209,97,70,156,65,0,184,16,2,0,0,29,80,120,2,4,65,176,28,20,2,195,160,8,0,3,55,128,0,27,116,23,7,0,0,79,48,18,138,64,0,115,0,22,154,7,65,152,128,21,210,142,65,160,116,36,1,35,208,50,61,0,227,16,48,6,139,192,56,200,0,5,177,147,208,68,22,7,65,96,1,32,2,242,128,100,220,0,96,1,125,180,160,0```

The shorter URLs I saved work - although of course, the length of the URL as potential source of the problem is just speculation from my side.

Would be nice if these could be made working. Browser is Firefox on Debian. Let me know if you need additional information.

**Comment by amoncaldas** [comment]
Hey @wmuni 

Thanks for reporting this.

By the default, the app compress/encode the URL parameters after the /data/ segment. But this can be changed in the app settings/advanced. 

As the data of URL you shared is compressed, it is difficult to check if the URL is correct or not. Running some checks, I noticed that the first URL you shared had 15 places and 18 coordinates. This was due to a bug that was limiting the max amount of places to 15. Therefore the URL generated was wrong and that is why it was not loading properly. This was fixed, but to test it you would have to generate a new URL, by adding places using the app interface.
