### ISSUE TITLE
Info modal propagates to iframe

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/ors-map-client#164]
When using an iframe, the flood activision info modal is displayed there as well.
As usually those are quite small (e.g. to show the location of a school, business, etc) it can take up a lot of the screen:
![grafik](https://user-images.githubusercontent.com/23240110/127628625-a13f0c43-034e-474f-b0ad-2e7c1fdccebb.png)

**Comment by amoncaldas** [comment]
The flood alert is not a feature present in the ors maps client repository , but it is a feature added via plugin in the HeiGIT map client (that is based on the ors maps client + custom plugins). Nevertheless, it was fixed there and already published.
