### ISSUE TITLE
Annoying Zoomout

### ISSUE THREAD

**Issue by hede753** [GIScience/ors-map-client#169]
My typical workflow is:
- add/modify a waypoint in a region
- zoom in to the old position
- add/modify a waypoint in the same region
- zoom in to the old position
- add/modify a waypoint in the same region
- zoom in to the old position
- etcetera

The thing is: with every action in the maps section ORS zooms out to the route overview, showing the complete route. That's really annoying if I want to tweak a specific segment only. 

Is there an option to let ORS _not_ zoom out to the whole route overview with every working step?

**Comment by DenisSouth** [comment]
as addition to this issue I would like to see current zoom as a digit, and be able to set it manually

**Comment by amoncaldas** [comment]
With the default options the app auto zoom to fit the features on the map when a route changes. But there is an option to disable this in https://maps.openrouteservice.org/#/settings **Map view and extra information**. So, each user can define what fits better for individual cases.
