### ISSUE TITLE
Route parameters are missing.

### ISSUE THREAD

**Issue by cbayerlein** [GIScience/ors-map-client#19]
Route parameters (like allowed surfaces and steepness) are missing. So users can only find routes with the default settings and thus often no route is found at all. I believe that's a very important feature, especially for wheelchair users.

**Comment by amoncaldas** [comment]
As I was not sure, I asked a colleague and checked the [API Playgroud docs](https://openrouteservice.org/dev/#/api-docs) and there currently there is not parameter to specify allowed surfaces and steepness.

**Comment by TheGreatRefrigerator** [comment]
Ah sorry @amoncaldas , i thought you were talking about general routing,

for the wheelchair we offer this options :
![grafik](https://user-images.githubusercontent.com/23240110/89819251-631b8700-db4b-11ea-8ad4-b4c5a24a9a0a.png)

Nested inside options:
```
"options":{"profile_params":{"restrictions":{"maximum_incline":2}}}}
```

**Comment by amoncaldas** [comment]
Thanks @TheGreatRefrigerator. Now it is clear. I will work on this soon @cbayerlein

**Comment by cbayerlein** [comment]
Awesome!

I just saw that on the pedestrian profile, some options are also missing, namely the "additional settings", which can be used to prioritize quiter routes. This feature is not directly connected to the wheelchair use case, but I still think that it's an important feature (which could actually be useful for wheelchair usres, too), and we shouldn't loose it in the new UI.

Same argument for the fuel saving options in the car profile (even as they are experimental)

**Comment by amoncaldas** [comment]
Done. Available for testing in develop branch and https://vue.openrouteservice.org
