### ISSUE TITLE
Make it possible to move the scope of the map easier without drag'n'drop or the need to swipe

### ISSUE THREAD

**Issue by cbayerlein** [GIScience/ors-map-client#21]
People who cannot use a pointing device or touch gestures should be able to move the scope of the map by other means. A possibility is to provide arrow buttons for the four main directions. These would move the scope accordingly.

**Comment by amoncaldas** [comment]
Considering that there are several aspects of accessibility that can be improved and that some of them maybe annoying to other users, I think that the best approach is to create an accessibility mode that could be activated with a single click.
Taking this into consideration, it would be good if a list of accessibility changes were created so that we can think it as a whole and plan accordingly.

**Comment by cbayerlein** [comment]
Good idea!

**Comment by amoncaldas** [comment]
Would you like @cbayerlein  to create a list of minimum accessibility features/aspects that  should be part of this mode?.

**Comment by cbayerlein** [comment]
I think that not many features need to be hidden because otherwise they would be disturbing for those who don't need them. Map movement arrows might be one of those features. But else... Keyboard support and a good tab order, semantic markup and meaningful and serializable document flow is helpful to everyone and doesn't disturb. Giving context options to places on a simple select is simply good UX/UI design (in general it's good practise to provide multiple ways to access a feature because different users have different experiences, habits and mental models).

So for now, we'd have only this item (#21) on the list, as the other two (#20 and #23) are more generally usability-issues and there's no need to switch them on or off or hide them in in a special mode. 

But it might grow over time. We might put a living document in the repo...

**Comment by cbayerlein** [comment]
I'd go for the second approach as we mainly target mobile users here and they might not have a keyboard (on-screen keyboard is only shown if an input field is focused).

However, for desktop users, keyboard shortcuts to move the map might also be convenient. Maybe we can do both...?

**Comment by amoncaldas** [comment]
The navigation via arrow has been added  There is an accessibility button over the map. When activated, the map moving arrows are displayed. Some more details:
- The accessibility button is the third in tabindex order (first place search, second directions)
- The accessibility mode will also enable the highlighting of focused inputs
- To disable this mode just hit again the accessibility button
Could you @cbayerlein please give me a feedback about it?
It is available on https://vue.openrouteservice.org

**Comment by cbayerlein** [comment]
The arrows work fine, thank you , that's a huge improvement in terms of accessibility! 👍 

However, I do have some comments on the accessibility button:

- the icon is a bit confusing, if you don't know what it does. Maybe add a tool-tip?
- as the button is tab-order 3, the focus disappears between the place search and the button. This should be made visible
- focus highlighting is very strong in accessibility mode and can be seen well. However it might be a too much in your face now (and now I understa:d why you didn't want to highliht the focus always). Maybe we can make it less prominent and tune it a bit down, still keeping it visible and have it always on?
