### ISSUE TITLE
Don't rely right mouse clicks for context menu options in the map

### ISSUE THREAD

**Issue by cbayerlein** [GIScience/ors-map-client#23]
Right now you can open a context menu to "route from here", "route to here" etc by right-clicking on the map. These options are very useful. However, there is no such event on smartphones or similar devices and we should always be agnostic of specific input devices. So, in situations like that, we should provide at least a second way of acceessing the options and features.

Regarding the context menu, we could move it to the info box which opens on left click (and touch) - momentarily, it shows the address of the place and gives the option to copy lon/lat or lat/lon coordinates. Maybe this info box can be extended by the context menu options in question.

**Comment by TheGreatRefrigerator** [comment]
> However, there is no such event on smartphones or similar devices and we should always be agnostic of specific input devices

actually you can "reproduce" a right click by pressing a bit longer with one finger.
But setting the points from this context menu still doesn't work on my phone

**Comment by amoncaldas** [comment]
As @TheGreatRefrigerator  said, the equivalent of the right click on smartphones is the long press event and on my tests it works. If it does not work on your device @TheGreatRefrigerator  you should tell me more details, maybe provide a video trying to use it. So, it is not a matter of using or not right click/lonpress, but check in which devices it is not working and make adjustments. Long press is a standard widely used in mobile applications.

**Comment by cbayerlein** [comment]
Thanks for the info; I'll try it out later. However, I still think we shouldn't rely on certain input devices. For example, I use a mouse emulation to control my smartphone. Unfortunately, due to my limitations in movement, I can only send left mouse clicks (and only point'n'click, so no dragging or swiping). In some apps, this mouse click is translated as a touch press event and in this case, it might work as you described. However, most of the time these two events are handled differently and thus, the long click is not handled as long press and in turn not as equivalent to right click.

As a basic concept of accessibility, I would still vote for a device-agnostic approach. 

Therefore I still think the best solution would be to move the options to the info box. 

This would make the UI more intuitive. Our preliminary user surveyshows that many user's don't even know that they can right-click on the map to open a context menu (I myself only found out by mistake on the desktop version, because my speech recognition software misunderstood me and made a right click instead of a left click). Right clicks on web interfaces are rather seldom  and users don't expect any (important) feature here.

**Comment by cbayerlein** [comment]
Just to let know, I tested on my device (Samsung Galaxy S8 with Google Chrome) with my assistive technology (R-Net BlueTooth mouse module) and long-click aka click-and-hold doesn't work as a replacement for right click. Probably it's handled differently from long-press because it's a mouse event and not a touch event. 

Of course, one can also blame Chrome for that, but that doesn't help and it's easier to find a better solution here. Keeping in mind that the way it is designed now has other negative implications, too.

So, @amoncaldas , I would kindly ask you to reopen this issue.
