### ISSUE TITLE
Add new-line-characters in the GPX-Download-File

### ISSUE THREAD

**Issue by pilian** [GIScience/ors-map-client#260]
The downloaded GPX-File shows all data in one or two lines. That’s very unhandy to check.

I propose a “new line character” after each GPX-Point.

**Comment by amoncaldas** [comment]
Hi @pilian 

The generated file is optimized to be as smaller as possible. It is also originally planned to be read by software and not by humans. There are a lot of beautifiers available, including online ones. So, in the case you want to explore the contents of the file you can use one.
I think it is not a good idea to add a new line after each point only for this purpose.

Kind regards,
Amon

**Comment by pilian** [comment]
Hi @amoncaldas,

you are right about software purposes.

But the interested users of Komoot or Outdooractive know the advantage of output files with seperate lines.

IMHO the additional filesize is acceptable. 
My last file has 12.000 trackpoints. The filesize increases by 12kB, that is 1.6 percent.

I have no problem to do the extensions in an editor myself.

Thanks.
