### ISSUE TITLE
Placing starting/destination points not working

### ISSUE THREAD

**Issue by albertodiazsaez** [GIScience/ors-map-client#263]
Since (at least) yesterday (2022/02/28) I can't put starting or destination points for navigation, or for the "reach" tab. I tried with right click, and using the left menu (clicking on the "map" icon right to the field).

A white dot appears, but nothing is filled on the form, and the "tack" for navigation does not appear, so it's impossible to make a route.

I tried in Firefox 96 and Chrome 97.

**Comment by TheGreatRefrigerator** [comment]
Hi @albertodiazsaez,
this is related to our geocoder, which is currently not working. After we fixed the issue everything will be working again (1-2days).

As a workaround for now, you can:
1. left-click the map
2. copy lon-lat coordinate from the appearing popup on the map (bottom right)
3. copy to the address input field
4. click the appearing entry

**Comment by TheGreatRefrigerator** [comment]
Refers to #264
