### ISSUE TITLE
Wenigumstadt in Germany is listed with wrong state

### ISSUE THREAD

**Issue by golden-spiral** [GIScience/ors-map-client#269]
When searching for village Wenigumstadt, it is listed as belonging to Hesse, yet it is part of Bavaria.  It is located on the border of the two states, a review of the data present in OSM did not reveal any reason why ORS is assigning it to Hesse.

**Comment by TheGreatRefrigerator** [comment]
Hi @golden-spiral,

this is a problem with the who's on first data our geocoder uses:
https://spelunker.whosonfirst.org/id/1393659815/

Please see this forum post for how to approach this.
https://ask.openrouteservice.org/t/wrong-state-for-adresses-from-bremen-germany/2880

Best regards

**Comment by golden-spiral** [comment]
Thank you, I was not aware of this.  I filed an issue on https://github.com/whosonfirst-data/whosonfirst-data/issues/1998
