### ISSUE TITLE
Styling of isochrones is a bit too colorful

### ISSUE THREAD

**Issue by koebi** [GIScience/ors-map-client#289]
When requesting more than one isochrone, colors seem random and do not reflect reachability in any way.
The coloring should be adapted to reflect this and be more aesthetically pleasing, e.g. as was done in the old deprecated client.

**Comment by amoncaldas** [comment]
It is not random. It just picks the next available color in a list of html colors provided by html-colors library.

As the number of polygons is not fixed and determined based on the input of the user, the code is selecting the next available colors from a list of html colors here https://github.com/GIScience/ors-map-client/blob/1ec61b7e7ec5e9b4d91715c3fe52b128b8ad425c/src/support/polygon-utils.js#L89 , based on the index of the polygon. One can hard code a list of colors and pick the next available color from this list.

**Comment by koebi** [comment]
As discussed, replicating info from the PR in the issue:
The leafleat-versions of both the classic and the new client seem to be the same, but a difference in the code can be observed:

In the classic client, the overlying `<div class="leaflet-pane leaflet-overlay-pane">` has an additional `style="opacity:0.5";`-attribute, all individual `<path>`s then have `fill-opacity="1"`.

The new client only sets `fill-opacity="0.2"` for the `<path>`s containing the polygons individually, leading to a stacking effect of opacities.

**Comment by rabidllama** [comment]
As discussed in the linked PR, we should probably look at doing a simplistic defined set of colours to use (up to 10 and in a linear gradient) rather than trying to do a programmatic scaling. The question now though is which colour scheme should be used?
