### ISSUE TITLE
Unify translation file syntax and use JSON correctly

### ISSUE THREAD

**Issue by koebi** [GIScience/ors-map-client#334]
The original message states:

> ich habe ein Problem mit den i18n Ordner, das Mir bekannte JSON Format 
> sieht nicht koscher aus. Das JSON nested structure file nutzt keine ' 
> sondern "

which translates to 
_I have a problem with the i18n-folders, the JSON format (which I know) is not quite kosher.
The JSON nested structure file doesn't use `'`_ (singlequotes, editor's note) _but `"`_ (doublequotes, editor's note).

It goes on to state that this is evident in [this file](https://github.com/GIScience/ors-map-client/blob/800b5aca05265f92475e52ac655df172956adec4/src/pages/maps/i18n/maps.i18n.de-de.js)

```
export default {
   maps: {
     pageTitle: 'Ors Maps',
     Places: 'Orte',
     isochrones: 'Isochronen',
     placeNameRequired: 'Ortsangabe benötigt',
     altitude: 'Höhenänderung',
     settings: 'Einstellungen',
     toggleAccessibleMode: 'Barrierefreien Modus aktivieren/deaktivieren',
     about: 'Über ors',
     updateSearch: 'Suche in dieser Gegend',
     updateSearchAfterZoomOrCenterChange: 'Suche nach Kartenbewegung aktualisieren',
     pageNotFound: 'Seite nicht gefunden. Überprüfen Sie, ob die URL unvollständig oder falsch ist'
   }
}
```

which should look like 
 
```
{
   "maps": {
     "pageTitle": "Ors Maps",
     "Places": "Orte",
     "isochrones": "Isochronen",
     "placeNameRequired": "Ortsangabe benötigt",
     "altitude: "Höhenänderung",
     "settings: "Einstellungen",
     "toggleAccessibleMode": "Barrierefreien Modus aktivieren/deaktivieren",
     "about": "Über ors",
     "updateSearch": "Suche in dieser Gegend",
     "updateSearchAfterZoomOrCenterChange": "Suche nach Kartenbewegung aktualisieren",
     "pageNotFound": "Seite nicht gefunden. Überprüfen Sie, ob die URL unvollständig oder falsch ist"
   }
}
```

It notes further that

> die Java Befehle `export default` sollten da nicht enthalten sein
> können wir uns an das Format halten?

which translates to

_the Java statement `export default` should not be there.
Can we stick to the Format?_

**Comment by TheGreatRefrigerator** [comment]
The files in the i18n folder are no JSON (JavaScript Object Notation) files but native JavaScript files.
As it's a `.js` and not a `.json` file, the export is needed to properly import it in other JS files.
