### ISSUE TITLE
Show current GPS position of user on the map 

### ISSUE THREAD

**Issue by redfrexx** [GIScience/ors-map-client#346]
Show the current GPS position of the user on the map (if gps is enabled), so it is easier for users to navigate along the route. Clicking the GPS Position button in the bottom right of the app, does not seem to do anything except showing the pop up window explaining what the button is for. Tested it with Android and Firefox.

**Comment by amoncaldas** [comment]
This feature was working before. Some recent change might have disabled/interfered on it.
