### ISSUE TITLE
“Direct to destination” vs. “Directions to destination”

### ISSUE THREAD

**Issue by joker234** [GIScience/ors-map-client#37]
Why are there the two terms for the same functionality, adding a point as destination to our places list: “Direct to destination” vs. “Directions to destination”

**Comment by amoncaldas** [comment]
Direct to destinations should apply for the case when there already a route and you want to recalculate the route from the selected starting point `directly` to a new target. This is in opposition to `append as destination`, that is another option.
Directions to destinations should be the term used to the case when the user will trigger an action of calculating the directions to a destination.

**Comment by joker234** [comment]
So these two UI decisions are on purpose?

![image](https://user-images.githubusercontent.com/2878899/94458117-ca51d100-01b5-11eb-9407-ad04862babb2.png)

**Comment by amoncaldas** [comment]
Sorry for the late reply.
Direct is used as an adverb. According the Merriam Webster dictionary:
 "from point to point without deviation : by the shortest way flew direct to Miami"
https://www.merriam-webster.com/dictionary/direct
