### ISSUE TITLE
Automatic interface switch from directions to place unintuitive

### ISSUE THREAD

**Issue by joker234** [GIScience/ors-map-client#38]
When I have a route and delete all but one of my places from the list, the interface automatically switches to the „Place details“. When I now click on “Directions to here” on any point, the remaining place is missing (compare #36).

I had that quite often when I wanted to find several routes one after another from the same starting place yesterday and it was really annoying to put in the starting place every time ;)

**Comment by joker234** [comment]
The same applies for a click on “Clear route”. I would assume I would clear the route and not change to a totally different panel.

**Comment by amoncaldas** [comment]
This falls into the same case of the #36 and is also intended to be like this.
