### ISSUE TITLE
changing the time slot for a route, former heat route is still visible

### ISSUE THREAD

**Issue by omzoqasd** [GIScience/ors-map-client#383]
## client: 
heal. PC.

## Reproduce:
- create route from A to B, and color code the route (heat appearance)
- change then the time slot

## Result:
Old route is still visible, new route not color coded:
![image](https://github.com/GIScience/ors-map-client/assets/68805985/f3492b26-c723-4b43-b8dd-ad5e1eff1aa6)

## Expectation:
unkown, what should happen?
Current design not intended as new route is not shown properly

**Comment by mrkhan** [comment]
resolved
