### ISSUE TITLE
Let user add a via point

### ISSUE THREAD

**Issue by mrkhan** [GIScience/ors-map-client#384]
Heal client
Steps to reproduce: 

1. Add start point and destination point
2. Right-click on other place on map 
3. click "Add Stop here" gives an error message "When using alternative routes option it is not possible to define route stops"

**Comment by TheGreatRefrigerator** [comment]
That's a ors backend issue. You can't use alternative routes with waypoints.
```JSON
{"error":{"code":2011,"message":"Parameter 'alternative_routes' is incompatible with parameter '(number of waypoints > 2)'."},"info":{"engine":{"build_date":"2023-07-09T01:31:50Z","version":"7.1.0"},"timestamp":1689071156894}}
```

**Comment by TheGreatRefrigerator** [comment]
Is this needed or nice to have?

**Comment by mrkhan** [comment]
Its needed. Planning to change `alternative_routes` to 1 if new stops points are added

**Comment by TheGreatRefrigerator** [comment]
> Its needed. Planning to change `alternative_routes` to 1 if new stops points are added

I think you would need to remove the whole `alternative_routes` object instead of setting `target_count` to 1.
