### ISSUE TITLE
Place search result restricted to Heidelberg region 

### ISSUE THREAD

**Issue by mrkhan** [GIScience/ors-map-client#386]
Place search results from Geocoding to restricted to Heidelberg region only

**Comment by mrkhan** [comment]
We can restrict the search result based on user's current bbox by modifying in ors-api-runner.js

**Comment by amoncaldas** [comment]
Instead of changing ors-api-runner.js, it can be done by using a simple plugin and one of the available evens:
https://github.com/GIScience/ors-map-client/blob/main/docs/plugins.md

**Comment by mrkhan** [comment]
Since the scope of the HEAL project is only limited to Heidelberg region, it doesn't matter even if we hard-code it. Writing a plugin for just this simple task seems overkill. 
But thanks for the suggestion, we keep this in mind for future work :)

**Comment by amoncaldas** [comment]
My comment was based on the fact that this issue is on main ors-map-client repo. 
Don't you have a dedicated repo for HEAL project?

**Comment by mrkhan** [comment]
No HEAL is just a separate branch on the main repo. as we need the most up-to-date core functionalities of the main app. ;)

**Comment by amoncaldas** [comment]
In the readme there is some information about how to have a dedicated repo synchronized with main repo. just some minutes is enough to create a plugin and there is an example in the plugin folder. By using these two things , you coud easily a dedicated repo, avoid changing the base application and keep everything synchronized, if desired.
