### ISSUE TITLE
Avoid ferries by default 

### ISSUE THREAD

**Issue by redfrexx** [GIScience/ors-map-client#388]
The clients suggests routes which include taking a ferry, e.g. when going from altstadt to Neuenheimer Feld. Since the user cannot choose to avoid ferries in the frontend of the HEAL ORS client, it would be better to avoid ferries by default when querying the routes. Adding the following parameter to the request should work:

```json
{"options": "avoid_features": ["ferries"]}
```

**Comment by mrkhan** [comment]
need following changes in `ors-map-filters.js` file 

```
name: 'avoid_features',
value: ['ferries'],
```
