### ISSUE TITLE
erronous walking route Oostkapelle, NL

### ISSUE THREAD

**Issue by HK53** [GIScience/ors-map-client#398]
Dear all,
reporting a map error/bug is quite a hassle...
no idea whether this is a bug.
on https://maps.openrouteservice.org/#/directions/Eeperkweg,Serooskerke,ZL,Netherlands/Molenweg,Serooskerke,ZL,Netherlands/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,102,0,232,5,96,3,128,54,124,0,103,60,139,240,19,159,1,217,143,192,26,98,4,97,56,226,1,102,111,212,153,38,204,1,51,16,13,196,88,131,126,220,187,151,229,209,152,241,156,121,243,175,193,149,42,66,36,50,226,29,136,8,0,29,83,192,136,155,14,80,0,188,160,5,181,196,172,197,232,16,1,155,192,3,110,139,130,3,229,10,128,11,64,14,236,143,224,13,100,128,14,106,98,5,238,131,238,141,14,136,134,4,23,137,153,2,226,229,155,14,139,2,0,11,238,84,0,0

openroute is proposing a walking route in error.  on this trajectory there is no foot path and no bike path. it is only for cars, and plain dangerous for walking/biking.

many thanks for your great service!

Henk

**Comment by sfendrich** [comment]
This looks like a data issue. While Eeperkweg is tagged with `bicycle=no` there is no tag indicating that one cannot walk along this street: https://www.openstreetmap.org/way/385851245
