### ISSUE TITLE
HEAL: Dragging (adapting) routes doesn't work

### ISSUE THREAD

**Issue by GrHalbgott** [GIScience/ors-map-client#421]
![image](https://github.com/GIScience/ors-map-client/assets/92852053/ca793028-4fbd-44ce-8023-141c3acf589f)

Dragging the route does not adapt the route. Instead, it displays a triangle of lines from each side of the segment (looks like a line). If these lines are clicked again, another set of lines is created without creating any waypoints. 

Related to #384, has been fixed for normal ORS with #12

HEAL

**Comment by TheGreatRefrigerator** [comment]
This was fixed in https://github.com/GIScience/ors-map-client/issues/439
but the problem still remains for the heal client, that you can't do waypoints + alternative routes, which is an ors issue.
