### ISSUE TITLE
HEAL: 3 routes in sidebar. two very similar

### ISSUE THREAD

**Issue by GrHalbgott** [GIScience/ors-map-client#427]
Usually, there are 3 optimized routes and the last two oftentimes are very similar. See pictures of one example:
![image](https://github.com/GIScience/ors-map-client/assets/92852053/51053ecf-8799-41f7-b3e3-2ba3c0032dbc)
![image](https://github.com/GIScience/ors-map-client/assets/92852053/14e602d7-cf1d-4d86-b5ed-49269d12ae5b)

The difference actually is there, but so minor, that it would make more sense to disregard the third route:
![image](https://github.com/GIScience/ors-map-client/assets/92852053/2741e542-6aed-4756-9409-709743dcd99d)

Are three routes enforced? Is there an efficient way to measure if the routes differ to a minimum amount and disregard one? Would it make sense that the third route is the recommended one with heat-score applied? Is this something that has to be fixed?

HEAL

**Comment by TheGreatRefrigerator** [comment]
I say this is rather an issue with the alternative route implementation in ors/graphhopper. As for 3 routes it only compares each of those to the original route when evaluating the share_factor:
(alternative route options are:)
![grafik](https://github.com/user-attachments/assets/54763b96-4323-4242-a730-a6e28fbf3372)

we could just set it to 2, which was my original suggestion as far as i remember. But sometimes theres a benefit to having an additional route to choose from.

**Comment by TheGreatRefrigerator** [comment]
Set to 2 now
