### ISSUE TITLE
Routing directions do not handle turn-arounds correctly

### ISSUE THREAD

**Issue by tomshouse** [GIScience/ors-map-client#446]
Route between these 2 addresses:
From: 3013 North Main Street, Wake County,NC,USA
To:     4728 Shady Greens Drive, Wake County,NC,USA

The instruction for the turnaround says " Continue straight onto North Main Street, US 401 "
when in fact this is 2 left turns, or a U-turn

**Comment by TheGreatRefrigerator** [comment]
Hi @tomshouse,

this is not an issue with the map client but the openrouteservice backend, that is still not resolved.
See this issue:
https://github.com/GIScience/openrouteservice/issues/728
