### ISSUE TITLE
Scale Bar

### ISSUE THREAD

**Issue by McLP2** [GIScience/ors-map-client#455]
It would be really nice to have a bar scale (https://en.wikipedia.org/wiki/Scale_(map)) on the map <3

**Comment by TheGreatRefrigerator** [comment]
Thanks for the suggestion @McLP2 ! Will definitely add that.
An advanced tool for measuring is already there:
![grafik](https://github.com/user-attachments/assets/418b0505-2276-4d27-a7bf-55f040fb2b8a)

**Comment by McLP2** [comment]
That was quick, thanks a lot! At low zoom levels, the scale seems a bit off (south pole has ~2x earth circumference), but that bug might be in Leaflet. Also, it is overlaid by the attribution footer on small (e.g. mobile) screens (especially with long attributions e.g. for satellite maps).
