### ISSUE TITLE
Display all places names with Latin characters

### ISSUE THREAD

**Issue by mecool1** [GIScience/ors-map-client#469]
It looks like there's no setting to display all places names with Latin characters.
I'd like to plan some hiking in Iran and the places names in Arabic are very cryptic to me.

Sorry if that option exists and I missed it.

**Comment by koebi** [comment]
Hey,

the map shown by default is the one that is displayed on openstreetmap.org as well, and they have made the decision to show place names in the local language (and script), and not a latinized version or an international name.

Whether you agree with this or not, I don't think this will be overturned soon (if ever).

Fortunately, you can switch the displayed map with the "Stack"-Symbol in the top right.
The "Outdoors"-style, for example, displays an international name as well.

You can also use any tile provider you like and change that in the settings, under "Advanced" -> "Custom tiles provider URL". There should be a few out there.

Remember to then switch to "Custom" in the Layer selection menu in the top right.

**Comment by koebi** [comment]
Addendum: Find a list of raster tile providers, w/ usable URLs, here: https://wiki.openstreetmap.org/wiki/Raster_tile_providers
