### ISSUE TITLE
Add vehicle type options in profile selection

### ISSUE THREAD

**Issue by amoncaldas** [GIScience/ors-map-client#47]
Add the vehicle type options for each profile that have this options, like HGV -> Googs, Bus, Heavey vehicle etc.

**Comment by TheGreatRefrigerator** [comment]
could also have another profile button for hgv and the other ones as sub profiles in the + button.
Clicking on one of them would set the correct `options.vehicle_type`

**Comment by amoncaldas** [comment]
The issue #51 will cover this.
