### ISSUE TITLE
Extra info shown on map missing segments

### ISSUE THREAD

**Issue by amoncaldas** [GIScience/ors-map-client#5]
![image](https://user-images.githubusercontent.com/13475791/87701971-0bcb0680-c799-11ea-9ab1-b2b5db66ef08.png)

**Comment by TheGreatRefrigerator** [comment]
when building the colored segments you are drawing them from e.g. waypoint 1-5 then 6-8 then 9-14
leaving the segments between point 5 and 6, 8 and 9 uncolored.
see e.g.
https://openrouteservice.org/map/#/directions/H%C3%BCttenbergweg,Deutschland/Buchbaumstra%C3%9Fe,Deutschland/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,78,0,232,2,96,21,128,54,1,153,136,5,128,118,114,0,224,1,156,242,110,113,128,104,106,45,231,153,214,43,78,128,70,98,141,24,208,13,196,82,171,58,131,42,54,28,216,168,210,60,250,85,42,217,104,170,164,105,73,5,196,4,0,14,169,224,68,77,135,40,11,208,32,3,55,128,6,221,46,112,1,60,195,186,64,7,48,5,166,135,68,8,5,119,118,70,133,49,2,119,65,119,67,12,67,2,243,193,118,68,192,198,203,136,2,242,128,5,181,197,20,96,5,243,42,0
and then show extra info on the map (using eye button)

**Comment by amoncaldas** [comment]
Fixed
