### ISSUE TITLE
Bug report: VueJS Maps embed code

### ISSUE THREAD

**Issue by shaedrich** [GIScience/ors-map-client#50]
I tested your VueJS Maps in beta and tried to get the embed code working but there are some weird things happening (I know, it’s still in beta): Whenever I try to embed a route with a starting place and a destination, the embed code only shows a round trip from the starting point back to the starting point.

**Comment by shaedrich** [comment]
Oh, it's not entirely prohibiting the user to do that, but not doing that automatically as it does with just one point. So it's rather a matter of usability, I guess.

**Comment by amoncaldas** [comment]
Hey @shaedrich  could you please provide the link that you got to be used to embed the map view? so we can discuss focused on a specific case. Thanks
