### ISSUE TITLE
FR: Ability to import csv with addresses

### ISSUE THREAD

**Issue by thibaultmol** [GIScience/ors-map-client#67]
Being able to just import a list of addresses in a csv or txt format would be nice (right now only routes can imported from what I understand).
I’d want to import that list and then change the order of the addresses to manually optimize my route.

**Comment by amoncaldas** [comment]
Hi @thibaultmol 

Although it is an interesting feature, it is not in our priority list at this moment. As the software is open source, you could potentially implement it and submit a push request with this feature.
