### ISSUE TITLE
FR: Ability to use optimization endpoint

### ISSUE THREAD

**Issue by thibaultmol** [GIScience/ors-map-client#68]
Being able to optimize a route from within this user friendly client would be a very useful addition.

**Comment by amoncaldas** [comment]
Hey @thibaultmol . Could you please give us more details about the optimization feature you would like see in the app? thanks

**Comment by thibaultmol** [comment]
I know that the ORS has an api for route optimizations. But it requires you to use the api directly, which a lot of people can't do (becaues of complexity). So being able to do it within the new map client would be a solution.

**Comment by TheGreatRefrigerator** [comment]
duplicate of #34
