### ISSUE TITLE
pick a location for reach doesn't work

### ISSUE THREAD

**Issue by MichaelsJP** [GIScience/ors-map-client#71]
The pick a location button within the reach functionality doesn't seem to work. At least not for me. Made some circles for you ;)...

![image](https://user-images.githubusercontent.com/22392104/107615421-74556580-6c4c-11eb-88b8-08249ad7bd44.png)

**Comment by amoncaldas** [comment]
You are right @MichaelsJP! Thanks. I will fix it soon.

**Comment by amoncaldas** [comment]
Fixed
