### ISSUE TITLE
Menu items not in full width / size

### ISSUE THREAD

**Issue by michaelzangl** [GIScience/ors-map-client#80]
In the menus, only the green area of menu items is clickable.

In most applications, menu items are full width.

![Bildschirmfoto von 2021-02-13 19-43-40](https://user-images.githubusercontent.com/5981823/107858351-f489ef80-6e33-11eb-9a33-a8f53cae27e9.png)

**Comment by amoncaldas** [comment]
Thanks for reporting. Corrected.
