### ISSUE TITLE
Add point / clearing point zooms out the map

### ISSUE THREAD

**Issue by michaelzangl** [GIScience/ors-map-client#82]
When:
* Clicking on the add point (+) button
* Clicking on the X next to a point
the map zooms out completely, since that point then seems to be at (0, 0). 

The map should stay in the current area, so that one can use the feature that allows to select a point on the map.

(In general, that automatic zooming feels very annoying and not intuitive. Zooming should not happen if the map already displays a useful area and every time you try to move a waypoint the map zooms out completely, which makes using the app for planning hiking / bike routes almost unusable)

**Comment by koebi** [comment]
There is a [related question in the ask-forum](https://ask.openrouteservice.org/t/routing-skips-to-0-0-when-a-point-to-a-route/2531), there seem to be more people facing the same issue :)

**Comment by amoncaldas** [comment]
Thanks for reporting. I will check this soon.

**Comment by amoncaldas** [comment]
Fixed
