### ISSUE TITLE
[openrouteservice] [Maps Website] Altitude window gets cleared on chosing alternative route from suggestions

### ISSUE THREAD

**Issue by JoergHW** [GIScience/ors-map-client#86]
Happens on Firefox and Chromium (both Linux).
How to reproduce:
Create a bicycle route with option 'bike'.
Use more than 1 alternative route, open altitude window.
Select a different alternative from the suggestions to see the elevation graph
--> windows stays open, but has no content

**Comment by amoncaldas** [comment]
Thanks for reporting. It will be checked soon.

**Comment by amoncaldas** [comment]
Fixed
