### ISSUE TITLE
[openrouteservice] [Maps Website] Deleting a waypoint removes the point before

### ISSUE THREAD

**Issue by JoergHW** [GIScience/ors-map-client#87]
Happens with Firefox and Chromium (both Linux).
How to reproduce:
Create a bicycle route with option 'bike', add some waypoints.
Remove a waypoint by clicking on the wastebasket right to it.
--> the point BEFORE gets removed. Very annoying, since the first waypoint removes the starting point instead!
(The starting point has no wastebasket. That should be added?!)

**Comment by JoergHW** [comment]
![ors-after](https://user-images.githubusercontent.com/17495690/108637166-c5a1f800-7489-11eb-9ef5-87a5f946d67b.png)
![ors-before](https://user-images.githubusercontent.com/17495690/108637167-c63a8e80-7489-11eb-9423-04db432bdfbb.png)

**Comment by amoncaldas** [comment]
Thanks for reporting. It will be checked soon.

**Comment by amoncaldas** [comment]
Fixed
