### ISSUE TITLE
Viewport move on route changes when not fitting bounds

### ISSUE THREAD

**Issue by steventebrinke** [GIScience/ors-map-client#89]
When I disable "Always fit bounds when route changes", a route change causes the viewport to move to the center of the route, without changing the zoom level. When you're zoomed in and add a waypoint at the beginning or end of the route, the added waypoint moves outside the viewport at the moment it's added. IMO this is quite strange, I would prefer the viewport not to move when it's not being fitted.

**Comment by amoncaldas** [comment]
Hopefully fixed via https://github.com/GIScience/ors-map-client/commit/84a9ee9a6213f2f3f1944ec90f70804b44958e4d
