### ISSUE TITLE
Route URL

### ISSUE THREAD

**Issue by jaimevives** [GIScience/ors-map-client#92]
With the classic map, I was generating route URLs easily using the URL parameters. For example:

https://classic-maps.openrouteservice.org/directions?a=39.512972,-0.46848,39.38107,-0.4012,39.38107,-0.4012,39.591932,-1.18927,39.654341,-0.594635,39.512972,-0.46848&b=4a&c=0&d=90&k1=es-ES&k2=km

Is this possible somehow with the new responsive map?

Thanks...

**Comment by TheGreatRefrigerator** [comment]
Hi @jaimevives,
there is the option to show the url in uncompressed format.
See https://ask.openrouteservice.org/t/how-to-track-polygon-like-official-map/2563/3

Not sure if all options are contained, but you should be to similarly create the url

**Comment by jaimevives** [comment]
Perfect! Many thanks...
