### ISSUE TITLE
missing OpenCycleMap on the new ui

### ISSUE THREAD

**Issue by Loki-Afro** [GIScience/ors-map-client#93]
Hey there, loving openrouteservice now for almost 4 years for planning my cycling routes.

However in the new ui i'm missing the OpenCycleMap layer i really prefer it over CycleOSM.

CycleOSM is good if you wanna look if there is a small official cyclepath, but in a densely packed city its just overwhelming. 
OpenCycleMap on the other hand is great for planning long distance trips where you may wanna stick to main cycle paths. 

Will it come back to the new ui?

**Comment by koebi** [comment]
This is not related to the ORS itself, but to the current client, so I transferred it over here :)

**Comment by amoncaldas** [comment]
Hey @Loki-Afro
You can add a custom tiles provider n the map settings and even make the custom provider as default. Then save it. This preference will be stored in your browser local storage and activated every time you reload the map client.

**Comment by Loki-Afro** [comment]
@amoncaldas
works - thank you

```
https://tile.thunderforest.com/cycle/{z}/{x}/{y}.png?apikey=xxx
```

I guess you removed it since it needs an apikey? 
Would like to see it added back to the standard providers though :)

**Comment by amoncaldas** [comment]
Just to make it clear: I'm a biker and I use the client too for bike routes :-). 
But having many tile providers on the list might be confusing for end users. As we have this custom option, each advanced users can add what is their preference.
