### ISSUE TITLE
Re-ordering waypoints imported from .gpx-file leads to error

### ISSUE THREAD

**Issue by koebi** [GIScience/ors-map-client#96]
Related to #94 and #95, when importing the same file, re-ordering waypoints that do pop up in the sidebar menu leads to `Mindestens ein Wegpunkt wurde nicht gefunden. Es sollte sich ein, für das Fahrzeugprofil zugänglicher, Weg in 350m Umkreis um jeden Wegpunkt befinden` shown in an error-box in the top right.

**Comment by amoncaldas** [comment]
Hopefully fixed via https://github.com/GIScience/ors-map-client/commit/84a9ee9a6213f2f3f1944ec90f70804b44958e4d
