### ISSUE TITLE
HGV settings like in the classic map

### ISSUE THREAD

**Issue by jaimevives** [GIScience/ors-map-client#98]
Hi:

  Are there plans to introduce the HGV settings like in the classic map? They are very useful, specially the height slider to avoid bridges with insufficient clearance (well, when the OSM map has the restriction in place, that is).

  Thanks...

**Comment by amoncaldas** [comment]
Added via https://github.com/GIScience/ors-map-client/commit/84a9ee9a6213f2f3f1944ec90f70804b44958e4d

**Comment by jaimevives** [comment]
Wow! That was really fast... Many thanks!

**Comment by jaimevives** [comment]
Hmmm... but it doesn't seems to affect the route. Here is an example with an infamous bridge:

https://maps.openrouteservice.org/#/directions/809%20W%20Morgan%20St,Durham,NC,USA/South%20Gregson%20Street,Durham,NC,USA/data/%7B%22coordinates%22:%22-78.90865802764894,36.000654870119476;-78.91026735305788,35.99676625134645%22,%22options%22:%7B%22profile%22:%22driving-hgv%22,%22preference%22:%22recommended%22,%22options%22:%7B%22profile_params%22:%7B%22restrictions%22:%7B%22axleload%22:1,%22height%22:5,%22length%22:2,%22weight%22:1,%22width%22:2,%22hazmat%22:false%7D%7D%7D,%22zoom%22:18%7D%7D

And here with the classic map:
https://classic-maps.openrouteservice.org/directions?n1=35.999566&n2=-78.911979&n3=17&a=36.000551,-78.908679,35.996567,-78.910257&b=4a&c=0&f3=5&k1=en-US&k2=km

**Comment by amoncaldas** [comment]
I noticed this and it was already fixed. you can click on the same link to the client (make sure to clear the cache)

**Comment by jaimevives** [comment]
Yes, it works fine now. Many thanks again... these settings are very useful for truckers.
